# Generated by Django 3.0.7 on 2020-06-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='spam_count',
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_reported', to=settings.AUTH_USER_MODEL)),
                ('spammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spammer', to='contacts.Contact')),
            ],
            options={
                'unique_together': {('reported_by', 'spammer')},
            },
        ),
    ]
