# Generated by Django 3.0.7 on 2020-06-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('users', '0002_auto_20200606_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
    ]
